"""
Script to call via command line for downloading content of website url to local file.
"""

from argparse import ArgumentParser

from src.fetchsite import FetchSite


def parse_args():
    parser = ArgumentParser(description="Downloading website content to local file")
    parser.add_argument("--url",
                        help="url of website to be donwloaded")
    parser.add_argument("--output_file",
                        help="Name of output. If left empty autogenerated.")
    parser.add_argument("--timestamp", action="store_true",
                        help="Adds timestamp of download to filename.")
    parser.add_argument("--output_dir",
                        help="Directory into which file is to be saved. Defaults to . ")

    arguments = parser.parse_args()
    return arguments


if __name__ == "__main__":
    args = parse_args()
    FetchSite(args.url).download_content().to_file(add_timestamp=args.timestamp,
                                                   file_name=args.output_file,
                                                   output_dir=args.output_dir)
